### ISSUE TITLE
Please release?

### ISSUE THREAD

**Issue by djzort** [perl5-dbi/DBD-Oracle#103]
Lets release now? Thanks @mjegh

**Comment by mjegh** [comment]
ok. I'll try and do it today but I might not get around to it until tomorrow (rather busy with $work at the mo). BTW, thanks for all the work you've done on D::O.

**Comment by mjegh** [comment]
Done

**Comment by mjegh** [comment]
ohoh. The dzil build process does not work Dean. It does not update NEXT in the Changes file, it does not update the Oracle version in Oracle.pm and it creates an incorrect version in MYMETA.*. Any ideas?

**Comment by mjegh** [comment]
Forget most of that. I've uploaded 1.79.

**Comment by djzort** [comment]
Just had a chance to look at this now. 

Thanks for making the release :)
