### ISSUE TITLE
Tag for v1.80

### ISSUE THREAD

**Issue by djzort** [perl5-dbi/DBD-Oracle#114]
Can the tag for 1.8 be pushed ?

**Comment by djzort** [comment]
@mjegh please?

**Comment by djzort** [comment]
ping @mjegh

**Comment by mjegh** [comment]
I believe it is tagged now.
I have not been at work since January and at present have very limited access to github.

**Comment by djzort** [comment]
yup it's there now. thanks @mjegh and all the best during these trying times.
