### ISSUE TITLE
Error during "make" in DBD:Oracle

### ISSUE THREAD

**Issue by kirandba-hub** [perl5-dbi/DBD-Oracle#117]
rm -f blib/arch/auto/DBD/Oracle/Oracle.so
LD_RUN_PATH="/u01/app/oracle/product/12.1.0/dbhome_1/lib:/lib/../lib64" cc  -shared -O2 -L/usr/local/lib -fstack-protector-strong  Oracle.o dbdimp.o oci8.o  -o blib/arch/auto/DBD/Oracle/Oracle.so  \
   -L/u01/app/oracle/product/12.1.0/dbhome_1/lib -lclntsh -ldl -lm -lpthread -lnsl -lirc -limf -lirc -lrt -lsvml   \

/usr/bin/ld: cannot find -lnsl
collect2: error: ld returned 1 exit status
make: *** [Makefile:524: blib/arch/auto/DBD/Oracle/Oracle.so] Error 1
[root@opensource-db DBD-Oracle-1.80]# cd ..

Please help me to solve this

**Comment by djzort** [comment]
`/usr/bin/ld: cannot find -lnsl`

Does the failure go away if you install the libnsl package?  Thanks.

it seems that fedora and friends like redhat have pulled it out of libc

**Comment by kirandba-hub** [comment]
Hi djzort,

The libnsl package is already isntalled,still i am facing the error

Last metadata expiration check: 4:33:51 ago on Tuesday 16 June 2020 07:27:02 PM IST.
Package libnsl-2.28-101.0.1.el8.x86_64 is already installed.

I'm not getting why i am receiving the error still?

**Comment by djzort** [comment]
you probably need to install the development package

**Comment by Tux** [comment]
`-lxxx` not found is mostly either a missing `-L/path/to/lib/localtion` or a mismatch in architecture: 32bit libs might exist but won't load on 64bit builds and vice versa). Check with the `file` command

**Comment by djzort** [comment]
yes hopefully its a pure 64bit system and you have installed the 64bit oracle client, youll have lots of problems if youre mixing 32bit

**Comment by kirandba-hub** [comment]
> yes hopefully its a pure 64bit system and you have installed the 64bit oracle client, youll have lots of problems if youre mixing 32bit

[root@opensource-db DBD-Oracle-1.80]# uname -a
Linux opensource-db.com 5.4.17-2011.1.2.el8uek.x86_64 #2 SMP Mon Apr 20 22:10:46 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux

And i installed the 64 bit client,i didn't have the 32 bit

**Comment by kirandba-hub** [comment]
> `-lxxx` not found is mostly either a missing `-L/path/to/lib/localtion` or a mismatch in architecture: 32bit libs might exist but won't load on 64bit builds and vice versa). Check with the `file` command

Can you help me how can i use 'file' command here.

**Comment by djzort** [comment]
afaik you need to install the libnsl-devel package to link against it. I think thats what redhat and friends call it

**Comment by kirandba-hub** [comment]
> I'm thinking it's something to do with your LD_LIBRARY_PATH. You typically only need to set the Oracle lib directory. In your case:
> LD_LIBRARY_PATH="/u01/app/oracle/product/12.1.0/dbhome_1/lib"

Means,should i change the LD_LIBRARY_PATH?

**Comment by whindsx** [comment]
> 
> 
> > I'm thinking it's something to do with your LD_LIBRARY_PATH. You typically only need to set the Oracle lib directory. In your case:
> > LD_LIBRARY_PATH="/u01/app/oracle/product/12.1.0/dbhome_1/lib"
> 
> Means,should i change the LD_LIBRARY_PATH?

Yes, but after you make sure you have libnsl-devel installed like @djzort mentioned.

**Comment by Tux** [comment]
On openSUSE TumbleWeed
```
% locate libnsl.so
/lib/libnsl.so.1
/lib64/libnsl.so.1
/usr/lib/libnsl.so.2
/usr/lib/libnsl.so.2.0.0
/usr/lib/oracle/12c/client-12.1.0/lib/stubs/libnsl.so
/usr/lib/oracle/12c/client-12.1.0/lib/stubs/libnsl.so.1
/usr/lib64/libnsl.so
/usr/lib64/libnsl.so.2
/usr/lib64/libnsl.so.2.0.0

% file /usr/lib64/libnsl.so
/usr/lib64/libnsl.so: symbolic link to libnsl.so.2.0.0

% rpm -qf /usr/lib64/libnsl.so
libnsl-devel-1.2.0-2.31.x86_64

% rpm -qf /usr/lib64/libnsl.so.2.0.0
libnsl2-1.2.0-2.31.x86_64

% file /usr/lib64/libnsl.so.2.0.0
/usr/lib64/libnsl.so.2.0.0: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=2b51757bc9f007741b2da0d1e956b0c3ae5820e8, not stripped
```
On CentOS-8.1
```
# dnf search libnsl
Last metadata expiration check: 0:33:10 ago on Tue 16 Jun 2020 09:45:01 PM CEST.
========================= Name Exactly Matched: libnsl =========================
libnsl.i686 : Legacy support library for NIS
libnsl.x86_64 : Legacy support library for NIS
======================== Name & Summary Matched: libnsl ========================
libnsl2-devel.i686 : Development files for libnsl
libnsl2-devel.x86_64 : Development files for libnsl
============================= Name Matched: libnsl =============================
libnsl2.x86_64 : Public client interface library for NIS(YP) and NIS+
libnsl2.i686 : Public client interface library for NIS(YP) and NIS+
libnsl2.x86_64 : Public client interface library for NIS(YP) and NIS+

# dnf install -y libnsl2 libnsl2-devel
:
:
Installed:
  libnsl2-devel-1.2.0-2.20180605git4a062cf.el8.x86_64
  libtirpc-devel-1.1.4-4.el8.x86_64

Complete!

# file /usr/lib64/libnsl*
/usr/lib64/libnsl-2.28.so:  ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=084062b15cae5808574fbf783d353ce22358b362, for GNU/Linux 3.2.0, not stripped, too many notes (256)
/usr/lib64/libnsl.so:       symbolic link to libnsl.so.2.0.0
/usr/lib64/libnsl.so.1:     symbolic link to libnsl-2.28.so
/usr/lib64/libnsl.so.2:     symbolic link to libnsl.so.2.0.0
/usr/lib64/libnsl.so.2.0.0: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=e24e23fc5955c8e181c09c283208f74885469b7d, stripped, too many notes (256)
```

**Comment by djzort** [comment]
how did you go?

**Comment by gitcnd** [comment]
You do not need nsl

Edit the makefile and remove -lnsl and it builds fine.

**Comment by djzort** [comment]
#120 is the same issue

**Comment by gitcnd** [comment]
Yeah - this #117 thread is full of red herrings.  #120 makes it a lot clearer what needs doing (and that #117 doesn't actually seem to be a real problem, since the dependency giving the problem isn't needed)

**Comment by cjbj** [comment]
libclntsh needs libnsl:

```
$ ldd ~/instantclient_19_8/libclntsh.so
	linux-vdso.so.1 =>  (0x00007ffee8570000)
	libnnz19.so => /home/cjones/instantclient/libnnz19.so (0x00007fec78de0000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fec78bdc000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fec788da000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fec786be000)
	libnsl.so.1 => /lib64/libnsl.so.1 (0x00007fec784a4000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fec7829c000)
	libaio.so.1 => /lib64/libaio.so.1 (0x00007fec7809a000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007fec77e80000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fec77ab2000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fec7d5f4000)
	libclntshcore.so.19.1 => /home/cjones/instantclient/libclntshcore.so.19.1 (0x00007fec77511000)
```

**Comment by gitcnd** [comment]
Finding libnsl for CentOS tripped me up (and, by the looks, everyone else as well)  - it's not that it isn't installed, but that someone messed something up in the journey from libnsl1 to libnsl2 (the not-needed -lnsl doesn't seem to understand that it's got nsl2 I think).

**Comment by cjbj** [comment]
If you install the `libnsl` package on Oracle Linux 8 (and therefore presumably on RH8) it will install the necessary link `libnsl.so.1`

**Comment by whindsx** [comment]
> 
> 
> If you install the `libnsl` package on Oracle Linux 8 (and therefore presumably on RH8) it will install the necessary link `libnsl.so.1`

I verified this worked with CentOS 8, instantclient-19.8, DBD-Oracle-1.80 and Perl-5.32.0.

`yum install libnsl`

**Comment by gitcnd** [comment]
I'm not using instantclient.  Maybe that's the clue to this error - perhaps that's why lots of people have it, and the developers didn't notice?  

FWIW - my CentOS 8 does have libnsl installed, but that error still blocks the build, and removing the lib from the make process completes fine.

**Comment by djzort** [comment]
RedHat decided to split the library out, this is not the case on Debian.

This is the same issue as #117

What are peoples suggestions for handling a missing library?

**Comment by whindsx** [comment]
> 
> What are peoples suggestions for handling a missing library?

For CentOS-8 (and I assume RH8) I suggest users simply install libnsl along with libnsl2:

```
[root@host ~]# yum info libnsl.x86_64 libnsl2.x86_64
This system is receiving updates from Red Hat Satellite or Spacewalk server.
Last metadata expiration check: 1:07:18 ago on Wed 05 Aug 2020 01:04:09 PM CDT.
Installed Packages
Name         : libnsl
Version      : 2.28
Release      : 101.el8
Architecture : x86_64
Size         : 192 k
Source       : glibc-2.28-101.el8.src.rpm
Repository   : @System
From repo    : centos-8-base
Summary      : Legacy support library for NIS
URL          : http://www.gnu.org/software/glibc/
License      : LGPLv2+ and LGPLv2+ with exceptions and GPLv2+ and GPLv2+ with exceptions and BSD and Inner-Net and ISC and Public Domain and GFDL
Description  : This package provides the legacy version of libnsl library, for
             : accessing NIS services.
             : 
             : This library is provided for backwards compatibility only;
             : applications should use libnsl2 instead to gain IPv6 support.

Name         : libnsl2
Version      : 1.2.0
Release      : 2.20180605git4a062cf.el8
Architecture : x86_64
Size         : 144 k
Source       : libnsl2-1.2.0-2.20180605git4a062cf.el8.src.rpm
Repository   : @System
From repo    : anaconda
Summary      : Public client interface library for NIS(YP) and NIS+
URL          : https://github.com/thkukuk/libnsl
License      : BSD and LGPLv2+
Description  : This package contains the libnsl library. This library contains
             : the public client interface for NIS(YP) and NIS+.
             : This code was formerly part of glibc, but is now standalone to
             : be able to link against TI-RPC for IPv6 support.
```
As long as RH maintains the libnsl legacy package then we should be fine. Also as stated above by @cjbj "A future version of Oracle client libraries won't depend on libnsl." at which point it won't be an issue (with new versions at least).

**Comment by gitcnd** [comment]
@djzort YOU DO NOT NEED THAT LIBRARY.

I have no idea why everyone keeps wasting our time by talking about how to install something that IS NOT USED.

        Edit the makefile and remove -lnsl and it builds fine.

**Comment by djzort** [comment]
> @djzort YOU DO NOT NEED THAT LIBRARY.
> 
> I have no idea why everyone keeps wasting our time by talking about how to install something that IS NOT USED.
> 
> ```
>     Edit the makefile and remove -lnsl and it builds AND WORKS fine.
> ```

Send a PR with your changes then? We can then smoke it and check it against different versions

**Comment by djzort** [comment]
After review, the nsl library is being detected by Makefile.PL from the local oracle install. It is not being added by Makefile.PL.

Unfortunately, nsl will continue to need to be installed to satisfy Oracle. There is nothing we can do.
