### ISSUE TITLE
CPAN / METACPAN documentation fails to make any mention of ORACLE_USERID

### ISSUE THREAD

**Issue by gitcnd** [perl5-dbi/DBD-Oracle#119]
There is also no obvious mention during the build process - just a ton of these useless errors:-

t/10general.t ............. skipped: Unable to connect to Oracle
t/12impdata.t ............. skipped: Unable to connect to Oracle
t/14threads.t ............. skipped: Unable to connect to Oracle
t/15nls.t ................. skipped: Unable to connect to Oracle
t/20select.t .............. skipped: Unable to connect to oracle
t/21nchar.t ............... skipped: Unable to connect to Oracle

And, note, when you finally do figure out how to test, it produces one more error:-

t/60reauth.t .............. skipped: ORACLE_USERID_2 not defined.

Now - that last error is useful!

1. Please fix the CPAN doc so we know how to use ORACLE_USERID
2. Please fix the tests, so they report the problem properly - "Unable to connect to Oracle, ORACLE_USERID not defined." would be WAY more useful.

Also note that to doc I did find is wrong

This does not work:-
    export ORACLE_USERID='scott/tiger'
This works (no apostrophes)
    export ORACLE_USERID=scott/tiger

**Comment by djzort** [comment]
Those tests are only useful if you want to test against a database which is not possible in cpantesters, but you are correct the messages aren't great and there's no mention in the POD

You can infer their usage from the travis config https://github.com/perl5-dbi/DBD-Oracle/blob/master/.travis.yml wherein we test against Oracle XE. If you are using DBD::Oracle internally and have a CI system configured, i encourage you to configure testing such that your specific client and server configuration are tested.

**Comment by djzort** [comment]
Its already mentioned in the README file and the t/README file

https://metacpan.org/source/MJEVANS/DBD-Oracle-1.80/README
https://metacpan.org/source/MJEVANS/DBD-Oracle-1.80/t/README
