### ISSUE TITLE
Oracle Instant client Version 21 is invalid

### ISSUE THREAD

**Issue by pau1ie** [perl5-dbi/DBD-Oracle#127]
Oracle have released version 21 of the instant client (bumped from 19). This fails the test for a sane looking Oracle version number in the install. The check is here:

https://github.com/perl5-dbi/DBD-Oracle/blob/026fdabb23200832cf53546ae0401f8de0fd1fb2/Makefile.PL#L1705

**Comment by pau1ie** [comment]
I note they aren't listed on the page, but that is the version I just got when I used the latest link.
https://www.oracle.com/uk/database/technologies/instant-client/linux-x86-64-downloads.html

**Comment by Tux** [comment]
https://www.oracle.com/database/technologies/instant-client/linux-x86-64-downloads.html shows them, so the /uk/ infix is problematic?

**Comment by Tux** [comment]
FWIW, I just tried
```
    if ($client_version_full && $client_version_full !~ m/^([789]|[12][0-9])\.[0-9]+/
```
and got here:
```
DBD-Oracle-git 520 > make test
"/pro/bin/perl5.28.0" -MExtUtils::Command::MM -e 'cp_nonempty' -- Oracle.bs blib/arch/auto/DBD/Oracle/Oracle.bs 644
PERL_DL_NONLAZY=1 "/pro/bin/perl5.28.0" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/00dbdoracletestlib.t .... ok
t/01base.t ................ ok
t/02versions.t ............ # OCI client library version: 21.1.0.0
t/02versions.t ............ 1/2 # Database version: Oracle Database 11g Enterprise Edition Release 11.2.0.3.0 - 64bit Production
t/02versions.t ............ ok
:
t/24implicit_utf8.t ....... skipped: Database character set is not Unicode
t/25plsql.t ............... 59/86
#   Failed test 'p1 ok'
#   at t/25plsql.t line 357.
#          got: ''
#     expected: 'Hello'

#   Failed test 'p2 ok'
#   at t/25plsql.t line 358.
#          got: ''
#     expected: 'Y'
# Looks like you failed 2 tests of 86.
t/25plsql.t ............... Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/86 subtests
t/26exe_array.t ........... ok
:
t/39attr.t ................ # Oracle version: 11.2.0.3.0
# client version: 21.1.0.0
t/39attr.t ................ ok
t/40ph_type.t ............. 1/17 Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Oracle::db handle .
t/40ph_type.t ............. ok
:
t/60reauth.t .............. skipped: ORACLE_USERID_2 not defined.
t/70meta.t ................ ok
t/80ora_charset.t ......... skipped: Database is set up as US7ASCII
t/rt13865.t ............... ok
t/rt74753-utf8-encoded.t .. skipped: Database character set is not Unicode
t/rt85886.t ............... ok

Test Summary Report
-------------------
t/25plsql.t             (Wstat: 512 Tests: 86 Failed: 2)
  Failed tests:  65-66
  Non-zero exit status: 2
Files=39, Tests=2200, 60 wallclock secs ( 0.38 usr  0.05 sys +  4.80 cusr  0.69 csys =  5.92 CPU)
Result: FAIL
Failed 1/39 test programs. 2/2200 subtests failed.
```

**Comment by Tux** [comment]
Also note that `tnsping` from the 19.0.0.0.0 distribution will dump core if you symlink `libclntsh.so.21.1` to `libclntsh.so.19.1` (and `libclntshcore`), something that worked rather well for previous versions.
I am still very annoyed that OIC does not include `tnsping`.

**Comment by cjbj** [comment]
> I am still very annoyed that OIC does not include tnsping.

Is it really worth it when SQL*Plus is available?  The debate internally comes up every now and again.

**Comment by cjbj** [comment]
Note that with the Instant Client 21c RPM packages, the directory path is now `/usr/lib/oracle/21/client64/lib` with no release update number after the `21`.

**Comment by Tux** [comment]
> Note that with the Instant Client 21c RPM packages, the directory path is now `/usr/lib/oracle/21/client64/lib` with no release update number after the `21`.

I noticed. Symbolic links help a lot.

As a developer, I'll explain (part of) the reasoning ...

When installing a new OIC, I - just like with java - want to keep the previous one (or two or three or more) around, so already running programs will work on just as if nothing happened. To ensure this, I make a complete backup of `/usr/lib/oracle` and `/usr/include/oracle`. Then I install the rpm's, which in most cases implies that I **have to** uninstall previous rpm's. When that is don I restore the backupup. This means that all new folders added by the newest rpm's are not affected by this restore and all works on as if nothing happened. Step 1 is now safely executed.

Now I want to check if my programs will work in the new OCI environment, so I start with symlinking the new libclntsh and libclntshcore to the versioned versions of my previous installs to see if the **runtime** will work with the new OCI version without rebuilding/relinking. This works painless inside a major release tree, like 19.3 → 19.6 → 19.9. Then I rebuild everything from scratch, so it will be linked against the newest libs. If that also all works, I start test cycles.

Note here that if I have 21.1 as current and 21.3 comes out, I could not follow that defensive path and risk outage. That is why I followed my usual routines and renamed `21` to `21.1`.

**Comment by Tux** [comment]
> > I am still very annoyed that OIC does not include tnsping.
> 
> Is it really worth it when SQL*Plus is available? The debate internally comes up every now and again.

Yes it is:
• `tnsping` does not connect to a database, it connects to a listener and shows the connection parameters. Its errors are clear and useful
• `sqlplus` does not work without username/password making it much harder to separate users and infrastructural maintainers, certainly when used from (monitoring) scripts.

**Comment by Tux** [comment]
https://github.com/perl5-dbi/DBD-Oracle/commit/406b546d9e31d10f0638dcb27d27d07c770f5535

**Comment by cjbj** [comment]
> I noticed. Symbolic links help a lot.

Everyone's use case differs and there is no perfect solution for everyone with RPMs.   ZIPs have more flexibility, of course.

Re tnsping: points noted and passed onto its owners.  It's been a long time since I've used it.  SQL*Plus with dummy username/password has been fine.  And with a valid un/pw, gives me more assurance the DB is available.

**Comment by nvx** [comment]
I noticed that the current latest release version fails to build against instantclient 21.1. Is simply cutting a new release that includes commit 406b546 enough to fix it, or are there other issues with DBD::Oracle and the new instantclient version?

**Comment by djzort** [comment]
Please try again with 1.82 on the CPAN
