### ISSUE TITLE
Can't load DBD::Oracle on macOS Catalina

### ISSUE THREAD

**Issue by carragom** [perl5-dbi/DBD-Oracle#128]
Hi there,

I built this module like this

```bash
export ORACLE_HOME=/usr/local/oracle/product/19.8/instantclient
cpanm DBD::Oracle
```

Then I tried to load it

```bash
perl -MDBD::Oracle -E 'say DBD::Oracle->VERSION'
```

And I get the following error

```text
Can't load '/usr/local/Cellar/perl/5.32.0/lib/perl5/site_perl/5.32.0/darwin-thread-multi-2level/auto/DBD/Oracle/Oracle.bundle' for module DBD::Oracle: dlopen(/usr/local/Cellar/perl/5.32.0/lib/perl5/site_perl/5.32.0/darwin-thread-multi-2level/auto/DBD/Oracle/Oracle.bundle, 1): Library not loaded: @rpath/libclntsh.dylib.19.1
  Referenced from: /usr/local/Cellar/perl/5.32.0/lib/perl5/site_perl/5.32.0/darwin-thread-multi-2level/auto/DBD/Oracle/Oracle.bundle
  Reason: image not found at /usr/local/Cellar/perl/5.32.0/lib/perl5/5.32.0/darwin-thread-multi-2level/DynaLoader.pm line 197.
 at -e line 0.
Compilation failed in require.
BEGIN failed--compilation aborted.
```

To fix it, I linked the library in the error to a well know lib location `/usr/local/lib` and now it works as expected

```bash
ln -s ${ORACLE_HOME}/libclntsh.dylib.19.1 /usr/local/lib/
perl -MDBD::Oracle -E 'say DBD::Oracle->VERSION'
```

Gives me

```text
1.80
```

A few questions comes to mind

1. Why does this module looks for `libclntsh.dylib.19.1` in `$ORACLE_HOME` at compile time but not at runtime?.
2. Is it possible for this module to include `$ORACLE_HOME` in the library lookup path at runtime?.
3. Am I just discovering something known to be impossible and should just be happy that it works at all? 😝

Thanks a lot for your time.

**Comment by hakonhagland** [comment]
See also [this](https://stackoverflow.com/q/66302271/2173773) question on stackoverflow.com.

The problem is that the `DYLD_LIBRARY_PATH` environment variable is not propagated to perl when running `make test` as described [here](https://stackoverflow.com/q/63629878/2173773). Instead of running `cpanm DBD::Oracle`, you can download the module run the tests manually using e.g. `prove`. The following worked for me (macOS BigSur 11.2.1), perlbrew perl version 5.32.0:

```
$ wget https://cpan.metacpan.org/authors/id/M/MJ/MJEVANS/DBD-Oracle-1.80.tar.gz
$ tar zxvf DBD-Oracle-1.80.tar.gz
$ cd DBD-Oracle-1.80
$ export DYLD_LIBRARY_PATH=/Users/hakonhaegland/Downloads/instantclient_19_8
$ export ORACLE_HOME=/Users/hakonhaegland/Downloads/instantclient_19_8
$ cpanm --installdeps .
$ perl Makefile.PL
$ make
$ prove -bv t  
$ make install
```

**Comment by carragom** [comment]
Thanks for the reply,
The part I'm actually curious about is, why when the module is compiled it does find the libraries in the `ORACLE_HOME` environment variable event when `DYLD_LIBRARY_PATH` is not defined, but at runtime it does not. Could it be possible to use the same logic at runtime to actually look in `ORACLE_HOME` for the libraries?

**Comment by djzort** [comment]
If you can develop a PR we can merge it no problems

**Comment by hakonhagland** [comment]
@djzort Added a PR to fix this. See PR #129.

**Comment by djzort** [comment]
Check out 1.82 on the CPAN

**Comment by carragom** [comment]
Hi,
There seems to be some discrepancy between the cpan distribution and the git repo. The line changed in #129 is included in the repo [Makefile.PL:436](https://github.com/perl5-dbi/DBD-Oracle/blob/v1.82/Makefile.PL#L436). But it looks like this in the tgz:

    $opts{LIBS} = [ "-L$OH -l$lib $syslibs" ];

I downloaded distribution from https://cpan.metacpan.org/authors/id/Z/ZA/ZARQUON/DBD-Oracle-1.82.tar.gz. Am I using the wrong URL or did I missed something ?

**Comment by djzort** [comment]
This is whats tagged. https://github.com/perl5-dbi/DBD-Oracle/blob/8857dbf90467f6b0b90dc132b3f61e7586aeaf1c/Makefile.PL#L436

And i also find that the line in the tarball is different. I suspect something was missed when releasing.

**Comment by carragom** [comment]
So what would be the next step here? Release a new version with the fix?

Thanks for your time.
