### ISSUE TITLE
WISHLIST Convert from travis to github actions

### ISSUE THREAD

**Issue by djzort** [perl5-dbi/DBD-Oracle#148]
Travis has long since stopped. It would be great it someone could help get github actions going.

**Comment by whindsx** [comment]
My main concern is to not get a lot of time/energy invested in something only to have it essentially pulled out from underneath us again.

I'm looking into GHA. I have some minor experience with it. Maybe I can at least get us something going.

**Comment by djzort** [comment]
GHA is what perl5 and raku are using so i think its a reasonable choice for now.

I would like a "strategic" decision for all of perl5-dbi/* but that may be asking too much for now.

**Comment by whindsx** [comment]
See [Build Latest](https://github.com/whindsx/DBD-Oracle/runs/5841179744?check_suite_focus=true) above for working GHA using an [Oracle service container](https://hub.docker.com/r/gvenzl/oracle-xe).


I got it working locally with the previous two Oracle install scripts but once I got it up to GHA it would fail when trying to configure the database. I never figured it out. Regardless the Oracle service container appears to be a far more efficient approach.

The InstantClient part needs some updating. Our Github source seems have stopped adding new packages at 19.6. Maybe somebody can point me to another source?  There's also a couple of other minor details I need to sort out.

So this works for the "latest" that we have of things. Shouldn't be too difficult to add more version permutations. 

Anyways please provide feedback. In the meantime I'll be putting this into a cleaned up PR.

**Comment by cjbj** [comment]
The Oracle Container Registry just released the prebuilt Oracle XE 21.3 container.  There is no clickthrough etc:

     podman pull container-registry.oracle.com/database/express:latest

I can't recommend 3rd party sources for Instant Client.  Just use the official links - there are no clickthroughs:

**Comment by djzort** [comment]
> See [Build Latest](https://github.com/whindsx/DBD-Oracle/runs/5841179744?check_suite_focus=true) above for working GHA using an [Oracle service container](https://hub.docker.com/r/gvenzl/oracle-xe).
> 
> I got it working locally with the previous two Oracle install scripts but once I got it up to GHA it would fail when trying to configure the database. I never figured it out. Regardless the Oracle service container appears to be a far more efficient approach.
> 
> The InstantClient part needs some updating. Our Github source seems have stopped adding new packages at 19.6. Maybe somebody can point me to another source? There's also a couple of other minor details I need to sort out.
> 
> So this works for the "latest" that we have of things. Shouldn't be too difficult to add more version permutations.
> 
> Anyways please provide feedback. In the meantime I'll be putting this into a cleaned up PR.

Looking really really good so far.

**Comment by Tux** [comment]
Side note: I do not have the energy to rewrite travis to whatever the best tool is today. If it is GHA, fine with me! I accepts PR's on any of the repo's in perl5-dbi, even DBI itself.

**Comment by djzort** [comment]
> Side note: I do not have the energy to rewrite travis to whatever the best tool is today. If it is GHA, fine with me! I accepts PR's on any of the repo's in perl5-dbi, even DBI itself.

This sounds like something someone might do on a perl foundation grant

**Comment by djzort** [comment]
Ive pulled the changes on to the branch... they may need to go on master though. 

I suspect there are settings that need to be made in the github settings too. tbd what they are
