### ISSUE TITLE
META.yml missing DBI as configure_requires and build_requires

### ISSUE THREAD

**Issue by mariominati22** [perl5-dbi/DBD-Oracle#155]
The current 1.83 version of DBD::Oracle is missing DBI as configure_requires and build_requires in META.yml, as you can see here: https://metacpan.org/release/ZARQUON/DBD-Oracle-1.83/source/META.yml

That is even so in the Makefile.pm those are defined: https://github.com/perl5-dbi/DBD-Oracle/blob/master/Makefile.PL#L58

This leads into errors if you try to install automatically with carmel or App::cpm in a CI/CD environment like Gitlab, Travis or most likely Github: https://github.com/skaji/cpm/issues/214

**Comment by djzort** [comment]
This should be resolved in d3b371805225325aa2937934dfd47cc7a2707ad8

**Comment by mariominati22** [comment]
Thanks, thats great and fast fix!

Is there already a release plan vor v1.90?

**Comment by djzort** [comment]
You can see the milestone for it here https://github.com/perl5-dbi/DBD-Oracle/milestone/1
