### ISSUE TITLE
Minor nits

### ISSUE THREAD

**Issue by davehodg** [perl5-dbi/DBD-Oracle#156]
The installer script reports that sqlplus cannot be run and various .dylibs loaded because "the developer cannot be verified". Probably worth documenting that it's Mac a Mac security thing.

And the Mac documentation should be brought up to date. We're on MacOS 12.5.1 now!

**Comment by davehodg** [comment]
I've cloned the repo, but I can't find 'README.macosx.txt' to make the text changes!

**Comment by djzort** [comment]
Check out https://github.com/perl5-dbi/DBD-Oracle/commit/aa8687e049b48b5a970ea2877e9c41ef1db8eae5
