### ISSUE TITLE
RHEL-9 ORA-28714: OCI_BATCH_ERRORS or OCI_RETURN_ROW_COUNT_ARRAY mode can only be specified for INSERT, UPDATE, DELETE or MERGE statement. (DBD ERROR: OCIStmtExecute)

### ISSUE THREAD

**Issue by tynarasimhareddy** [perl5-dbi/DBD-Oracle#170]
Getting below error after migrating the host from CentOs-7 to RHEL-9:
`ORA-28714: OCI_BATCH_ERRORS or OCI_RETURN_ROW_COUNT_ARRAY mode can only be specified for INSERT, UPDATE, DELETE or MERGE statement. (DBD ERROR: OCIStmtExecute)`

Use case:
We are trying to run execute_array() method to execute a stored procedure for array of users here. This piece code is working from decades on CentOs-7, but started failing after migrating the environment to RHEL-9.

Below are the rpms installed on RHEL-9 setup:
* oracle-instantclient19.19-basic-19.19.0.0.0-1.el9.x86_64.rpm
* oracle-instantclient19.19-devel-19.19.0.0.0-1.el9.x86_64.rpm
* perl-DBD-Oracle-1.80-2.el9.x86_64.rpm
* perl-DBI-1.643-9.el9.x86_64

Code at high level looks like below:

```
sub exec_procedure_array {
    my $dbh         = shift;
    my $procedure   = shift;
    my @param_array = @{(shift)};

    my @tuple_status = ();
    my $sth = _prepare_statement($dbh, "BEGIN $procedure; END;");
    eval {
        for my $i (1 .. scalar(@param_array)) {
            $sth->bind_param_array($i, $param_array[$i - 1]);
        }
        $sth->execute_array({ArrayTupleStatus => \@tuple_status});
    };
```

Could someone assist on this please.

**Comment by whindsx** [comment]
I would guess one of your dependencies got upgraded when you went from CentOS-7 to RHEL-9. Do you know what version DBD::Oracle you were previously on? I'd look there first and maybe try downgrading (v1.74 is good).

Also can you share what _prepare_statement() does?

**Comment by tynarasimhareddy** [comment]
> I would guess one of your dependencies got upgraded when you went from CentOS-7 to RHEL-9. Do you know what version DBD::Oracle you were previously on? I'd look there first and maybe try downgrading (v1.74 is good).
> 
> Also can you share what _prepare_statement() does?

Hi @whindsx 
Thank you for looking into the issue.
Currently we use perl-DBD-Oracle-1.62-3.el7.x86_64 on CentOs-7.

Below is the _prepare_statement() code snippet:
```
sub _prepare_statement {
    my $dbh       = shift;
    my $statement = shift;

    my $sth;
    my $attempt = 0;
    my $retries = 3;
    while (TRUE) {
        eval {$sth = $dbh->prepare($statement);};

        last if ($sth or $attempt >= $retries);

        WARN "Couldn't prepare statement '$statement': " . $dbh->errstr;
        $attempt++;
        INFO "Retrying (attempt #$attempt) in 10 seconds...";
        sleep $release_config{10};
    }

    unless ($sth) {
        ERROR "Failed to prepare statement '$statement': " . $dbh->errstr;
        return undef;
    }

    DEBUG "Prepared statement '$statement' successfully";
    return $sth;
}
```

**Comment by whindsx** [comment]
Now I'm leaning more towards an issue with Oracle instantclient. 11.2 to 19.19 is a pretty big jump. I would try an older supported version like 12.2.

Not ruling out a bug with DBD::Oracle and execute_array(), but if things work for you with 12.2 then that narrows it down.

**Comment by tynarasimhareddy** [comment]
Hi @whindsx 
19.19 is the certified client for RHEL-9 hosts. So we would not be able to downgrade to 12.2.

I tried upgrading DBD::Oracle to the latest v1.83 version and it still failed with same error.

**Comment by djzort** [comment]
DBD-Oracle-1.62 is ancient. Please upgrade and create a new issue.

**Comment by tynarasimhareddy** [comment]
> DBD-Oracle-1.62 is ancient. Please upgrade and create a new issue.

Hi @djzort 
As updated in the latest [comment](https://github.com/perl5-dbi/DBD-Oracle/issues/170#issuecomment-1966261661), we are experiencing the same issue with latest v1.83 version of DBD::Oracle.
