### ISSUE TITLE
please publish cand-v1.90 as an official release

### ISSUE THREAD

**Issue by damil** [perl5-dbi/DBD-Oracle#172]
Hi, 

Cand-v1.90 has been around for more than one year. Is there any blocking factor that prevents from making it a new official release ?

At my company we encounter the SEGV bug already reported in #111 and already solved in https://github.com/perl5-dbi/DBD-Oracle/pull/150 . Version 1.90_5 indeed shows no bug, while version 1.83 still has the problem. But I cannot really advise to deploy a development version on the production servers. So an official release including this fix would be greatly appreciated.

Thanks in advance, Laurent D.

**Comment by djzort** [comment]
Done.

**Comment by damil** [comment]
> Done.

That's great news, thanks !
... but is it published on CPAN ? I don't see it at https://metacpan.org/recent
