### ISSUE TITLE
1.74 problem

### ISSUE THREAD

**Issue by wileycoyote** [perl5-dbi/DBD-Oracle#21]
Hi, I get the following error message:

DBD::Oracle::st execute failed: ORA-06502: PL/SQL: numeric or value error: host bind array too small
ORA-06512: at line 3 (DBD ERROR: OCIStmtExecute) [for Statement "
        BEGIN
            Pck_Ltr_Production.Get_Live_Lett_Codes_By_Parent( :id, :table );
        END;

where :table is an array defined as an inout parameter.

running DBD::Oracle 1.74 on a 10.2 Oracle client, CentOS release 6.4

Running against 1.68 is fine.

Regards, Roger

**Comment by djzort** [comment]
The git situation has been resolved, so half a decade later this can be solved :)
