### ISSUE TITLE
Issue on t/rt85886.t in 1.74

### ISSUE THREAD

**Issue by poyntesm** [perl5-dbi/DBD-Oracle#26]
[root@epoml02 DBD-Oracle-1.74]# rpm -q perl
perl-5.10.1-129.el6.x86_64
[root@epoml02 DBD-Oracle-1.74]# rpm -q perl-DBI
perl-DBI-1.609-4.el6.x86_64
[root@epoml02 DBD-Oracle-1.74]# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 6.4 (Santiago)
[root@epoml02 DBD-Oracle-1.74]# 

Oracle is 11.2.0.4

I am seeing a failure on one test

t/rt85886.t ................... 1/2 
# Failed test 'ivok'
# at t/rt85886.t line 47.

SV = PV(0x2a57eb8) at 0x2b268f8
  REFCNT = 1
  FLAGS = (POK,pPOK)
  PV = 0x2b32f30 "1"\0
  CUR = 1
  LEN = 8
# Looks like you failed 1 test of 2.

t/rt85886.t ................... Dubious, test returned 1 (wstat 256, 0x100)

**Comment by mjegh** [comment]
If you don't use DiscardString and bind types as integer this won't matter.

The version of Oracle database should not matter here.

However, what version of DBI are you using?

**Comment by poyntesm** [comment]
hi there, here are the details
```
# B                                             => 1.22       (want any version)
# Carp                                          => 1.11       (want any version)
# DBI                                           => 1.609      (want 1.51)   
# Data::Dumper                                  => 2.124      (want any version)
# Devel::Peek                                   => 1.04       (want any version)
# DynaLoader                                    => 1.10       (want any version)
# Encode                                        => 2.35       (want any version)
# Exporter                                      => 5.63       (want any version)
# ExtUtils::MakeMaker                           => 6.55_02    (want 6.30)   
# Math::BigInt                                  => 1.89       (want any version)
# Test::More                                    => 1.001014   (want 0.88)   
# Thread::Semaphore                             => 2.09       (want any version)
# lib                                           => 0.62       (want any version)
# strict                                        => 1.04       (want any version)
# utf8                                          => 1.07       (want any version)
# vars                                          => 1.01       (want any version)
# warnings                                      => 1.06       (want any version)


t/rt85886.t ................... 1/2 
#   Failed test 'ivok'
#   at t/rt85886.t line 50.
SV = PV(0xf12ad8) at 0xf144b0
  REFCNT = 1
  FLAGS = (POK,pPOK)
  PV = 0xfecc50 "1"\0
  CUR = 1
  LEN = 8
# is_iv=0
# Looks like you failed 1 test of 2.
t/rt85886.t ................... Dubious, test returned 1 (wstat 256, 0x100)
```

**Comment by mjegh** [comment]
I think your copy of 'B' is too old. I had not realised this and so there is no requirement for a newer B.

Could you try upgrading B? I have 1.48 but you might not need one quite that new.

**Comment by poyntesm** [comment]
Forgive me if I am missing something, however how can I upgrade "B", is it not a core module an so I need to upgrade entire perl version to get newer B version? I am in enterprise environment and so stuck with perl 5.10.1 coming with RHEL6

**Comment by mjegh** [comment]
B, is just a module like anything else (see https://metacpan.org/pod/B). You can upgrade it without changing Perl. However, as I said, this test only matters if you intend to use DiscardString and as far as I know the only code which does this is some darkpan code. I would just ignore the failure if I were you.

**Comment by kjetillll** [comment]
Maybe the if-else in sub is_iv should be:
if (wantarray) {    return ($flags & (SVf_IOK|SVf_NOK|SVf_POK), $x) }
else {  return $flags & (SVf_IOK|SVf_NOK|SVf_POK)  }

I'm just guessing here and dont know much about perl internals, but it seemed strange to import SVf_NOK and SVf_POK without using them.

**Comment by mjegh** [comment]
Those imports are just not required. I will fix that.

**Comment by mohawk2** [comment]
@mjegh Did that happen? :-) If so can the issue now be closed?

**Comment by mjegh** [comment]
@mohawk2 I've no idea. I don't have much to do with DBD::Oracle these days. The current maintainer doesn't seem to do releases and I've pretty much given up submitting any changes.

**Comment by mohawk2** [comment]
I think there's a need for a new maintainer. Are you on the mailing list?

**Comment by mjegh** [comment]
@mohawk2 I am on  the mailing list if you mean the DBI one. I've been down this road before. I've contributed a lot of the code changes over the last 10+ years and it has been problematic as the assigned maintainer in most cases has not been a C coder although with John and Yanick we at least got releases out. There has not been one release since the latest new maintainer despite some poking. I even did a couple of development releases to try and get things moving. My company relies heavily on this module and we've been keeping our own version for years now because of the lack of movement. I'm now struggling to pull changes into our code because the differences are now so great. There have been a lot of good contributions which are worth releasing.

**Comment by mohawk2** [comment]
@mjegh Would you be willing to be the maintainer? If so, why not offer on the DBI list? Last release was in 2014 by current maintainer.

**Comment by mjegh** [comment]
Last release was not technically the current maintainer but I can see how you'd think that. I have been a co maintainer for ages but I have only done development releases (at the request of others). The situation isn't as straight forward as you might think and can only really be resolved by one person. I suggest if you are unhappy with the current situation you mail the dbi-dev list or Tim Bunce as I have done all I can and am tired of the whole thing. I do what I can, when I can but I've pretty much given up on seeing a DBD::Oracle release to the CPAN.

**Comment by mohawk2** [comment]
@timbunce What are your thoughts?

**Comment by djzort** [comment]
This is ancient history. Lets please close it
