### ISSUE TITLE
primary_key is not caseless for $table

### ISSUE THREAD

**Issue by Tux** [perl5-dbi/DBD-Oracle#40]
That is not documented, and even the tests themselves do a workaround this annoying Oracle issue:
```
t/20select.t
94:my @pk = $dbh->primary_key(undef, $dbh->{USER}||$dbh->{Username}, uc $table)
```
I think DBD::Oracle should overload primary_key_info to make sure $table is case-insensitive

**Comment by djzort** [comment]
I have noticed this and its annoying. I'm not certain its a good idea to hide oracle sql insanity. 

What do other drivers do?

**Comment by djzort** [comment]
Let's close this for now without a PR
