### ISSUE TITLE
Erro after compilation on SUSE Linux Enterprise Server 11 SP3  (ppc64)

### ISSUE THREAD

**Issue by LucianoMittmann** [perl5-dbi/DBD-Oracle#52]
install_driver(Oracle) failed: Can't load '/usr/lib/perl5/site_perl/5.10.0/ppc64-linux-thread-multi/auto/DBD/Oracle/Oracle.so' for module DBD::Oracle: /usr/lib64/oracle/10.2.0.5/client/lib/libocci.so.10.1: undefined symbol: __IBMCPlusPlusExceptionV2 at /usr/lib/perl5/5.10.0/ppc64-linux-thread-multi/DynaLoader.pm line 203.
 at (eval 3) line 3
Compilation failed in require at (eval 3) line 3.
Perhaps a required shared library or dll isn't installed where expected

**Comment by whindsx** [comment]
We would probably need to see more of your build output. Also what source were you installing from (Github, CPAN)?

**Comment by djzort** [comment]
@mjegh i think just close this

**Comment by mjegh** [comment]
Close. No reponse in over a year.
