### ISSUE TITLE
Incorrect reference to DBD::Pg in POD

### ISSUE THREAD

**Issue by psteiner** [perl5-dbi/DBD-Oracle#53]
The POD describing **bind_param** refers to "DBD::Pg" in 3 places. I believe the refernces should be to "DBD::Oracle":

First:
>If you need something else, you must use one of the values provided by DBI or by DBD::Pg. To use a SQL value, modify your "use DBI" statement at the top of your script as follows:

Second:
>To use Oracle SQL data types, import the list of values like this:
> `use DBD::Pg qw(:ora_types);`

Third:
> Examples:
>  `use DBI qw(:sql_types);`
>  `use DBD::Pg qw(:ora_types);`

**Comment by djzort** [comment]
These all seem to be fixed in git...

**Comment by djzort** [comment]
This is fixed, can someone please close it?

**Comment by djzort** [comment]
@mjegh this can be closed
