### ISSUE TITLE
Small change to t/25plsql.t

### ISSUE THREAD

**Issue by kjetillll** [perl5-dbi/DBD-Oracle#56]
The second test in t/25plsql.t with the name "ref = sql" should perhaps be changed from

is("@r", "@s2", "ref = sql");

into something like:

is(join(" ",sort@r), join(" ",sort@s2), "ref = sql");

Or else it fails. At least on my setup:

* docker image sath89/oracle-ee-12c
* ubuntu16.04 standard perl 5.22 in the host (not docker guest)
* dbd-oracle 1.74 and 1.75_2

**Comment by djzort** [comment]
^ have a PR

**Comment by djzort** [comment]
@mjegh this can be closed as its already merged
