### ISSUE TITLE
i been working on this for 3 hours.

### ISSUE THREAD

**Issue by nuzulfikrie** [perl5-dbi/DBD-Oracle#58]
Hi , i somehow cannot get pass the CANNOT FIND OCI . 

Somehow , when i try 'perl Makefile.PL' it keeps complaining it cannot find the OCI, figures that it tries to find sdk folder, so i copied it. 

Then it complains Could not find or create liboci.a. . 

I find it hard to link this to xampp in WIN 10. 

please help.

**Comment by whindsx** [comment]
What version of Oracle Client are you using? I know they tend to move stuff around.... There are lots of issues with this module and getting it built/installed...

**Comment by nuzulfikrie** [comment]
oracle client v12. on windows 10, perl module in xampp. i tried changing the makefile, so that it able to find the OCI then it complains cannot create liboci.a

**Comment by djzort** [comment]
2+ years old. closing
