### ISSUE TITLE
Segfault with t/58object.t

### ISSUE THREAD

**Issue by djzort** [perl5-dbi/DBD-Oracle#65]
if the $dbh->disconnect is removed from the end of t/58object.t then perl will segfault at the end of the test (in DESTROY i am guessing)

my environment:
perl 5.24.1 (debian stretch)
x86_64
oracle sdk 12.2

**Comment by abraxxa** [comment]
The same here
Ubuntu 18.04 x86_64
self-compiled unthreaded Perl 5.28.0
Oracle InstantClient 18.3.0.0.0
DBD::Orace 1.75_40

Same setup with 1.74 works fine.

**Comment by ribasushi** [comment]
> if the $dbh->disconnect is removed from the end of t/58object.t then perl will segfault 

@djzort if you include this change in a devrel - then my ASAN rig could pick this up as well. A run under ASAN will give you very descriptive "this is what happened and where to fix" hints.

Alternatively you could simply replicate my setup in the CI of DBD::Oracle and have this protection going forward: https://github.com/Perl5/DBIx-Class/commit/2e629b86f1e83b25e9ab92747ffaac7b87155693#diff-354f30a63fb0907d4ad57269548329e3

**Comment by djzort** [comment]
I am working to get a dev release out. But alas dev releases are going out via the cpan gods, because we/I dont have COMAINT and no one from pythian is answering/watching.

**Comment by ribasushi** [comment]
> because we/I dont have COMAINT

This is not how CPAN works. Anyone and their parrot can upload anything to their home directory without restriction. That Includes both `DBD-Oracle-1.75_42.tar.gz` and `DBD-Oracle-666.tar.gz`. The first one will be available to `cpanm --dev`, the second won't be.

Permissions only come in play when indexing is involved. Indexing is only involved when the version doesn't signify a devrel. This is what the "Unauthorized" means on metacpan as well:

**Comment by djzort** [comment]
Youre right, it just seems impolite. Anyway:



The uploaded file

    DBD-Oracle-1.75_42.tar.gz

has entered CPAN as

  file: $CPAN/authors/id/D/DJ/DJZORT/DBD-Oracle-1.75_42.tar.gz
  size: 410948 bytes
   md5: 1c9146f725f32e479178a2c0dc4b4352
  sha1: a447e69c8f847a82a64eb48cb0efb5002fd38f36

CPAN Testers will start reporting results in an hour or so:

  http://matrix.cpantesters.org/?dist=DBD-Oracle

Request entered by: DJZORT (Dean Hamstead)
Request entered on: Wed, 22 Aug 2018 06:30:28 GMT
Request completed:  Wed, 22 Aug 2018 06:30:38 GMT

Thanks,
-- 
paused, v1049

**Comment by mjegh** [comment]
I believe I might have COMAINT although I've not used it in years.

**Comment by djzort** [comment]
It seems that:
DBIML is owner via first-come
MJEVANS is co-maint
PYTHIAN is co-maint
TIMB is co-main

Im not sure if thats listed anywhere public, its in pause though (which is basically public)

**Comment by mjegh** [comment]
Yup, MJEVANS is me.

**Comment by djzort** [comment]
@mjegh could you please join us in #dbd-oracle on irc.perl.org ? we are conspiring to make a release

**Comment by mephinet** [comment]
I am also seeing segfaults on global destroy in an application at $work after upgrading from 1.74 to 1.76. I [bisected](https://github.com/pythian/DBD-Oracle/files/2617535/bisect.log) my way between cb011d20944a969d80278dadedcc3c624598b63a and 43a7127f254d9ba22ca140dcaf46bd4873aa3d70 - and according to that, b07d637fac1741256860fc755e28888b892180f4 is the first bad commit.                                                         
In gdb, the [backtrace.txt](https://github.com/pythian/DBD-Oracle/files/2617536/backtrace.txt) comes from perl_destruct, and passes ora_db_disconnect.

**Comment by almirus** [comment]
some problem for me
trace for DBD::Oracle 1.74 
.....
!   >> DESTROY     DISPATCH (DBI::dr=HASH(0x33b3380) rc1/1 @1 g2 ima10004 pid#22496) during global destruction
    >> DESTROY DBI::dr=HASH(0x33b3380) clearing 1 CachedKids
!   -> DESTROY in DBD::_::common for DBD::Oracle::dr (DBI::dr=HASH(0x33b3380)~INNER) thr#1e57010
!   <- DESTROY= ( undef ) [1 items] during global destruction
    DESTROY (dbih_clearcom) (drh 0x33b3308, com 0x33e2ff0, imp global destruction):
       FLAGS 0x102215: COMSET Active Warn PrintWarn ShowErrorStatement AutoCommit
       PARENT undef
       KIDS 1 (1 Active)
    dbih_clearcom 0x33b3308 (com 0x33e2ff0, type 1) done.
!   >> DESTROY     DISPATCH (DBIx::ContextualFetch::db=HASH(0x33e60c0) rc1/1 @1 g2 ima10004 pid#22496) during global destruction
!   -> DESTROY for DBD::Oracle::db (DBIx::ContextualFetch::db=HASH(0x33e60c0)~INNER) thr#1e57010
        OCISessionEnd(34b8d98,34b8e80,34f8700,mode=DEFAULT 0)=SUCCESS
        OCIServerDetach(34b9e40,34b8e80,mode=DEFAULT,0)=SUCCESS
        OCIHandleFree(34f8700,OCI_HTYPE_SESSION)=SUCCESS
        OCIHandleFree(34b8d98,OCI_HTYPE_SVCCTX)=SUCCESS
        OCIHandleFree(34b9e40,OCI_HTYPE_SERVER)=SUCCESS
        OCIHandleFree(34b8e80,OCI_HTYPE_ERROR)=SUCCESS
!T  <- DESTROY= ( undef ) [1 items] during global destruction
    DESTROY (dbih_clearcom) (dbh 0x33e60d8, com 0x33ea690, imp global destruction):
       FLAGS 0x1e22d1: COMSET Warn ChopBlanks RaiseError PrintWarn ShowErrorStatement AutoCommit TaintIn TaintOut
       PARENT undef
       KIDS 0 (0 Active)
       LongReadLen 2097152
    dbih_clearcom 0x33e60d8 (com 0x33ea690, type 2) done.
!   >> DESTROY     DISPATCH (DBI::dr=HASH(0x33b3308) rc1/1 @1 g2 ima10004 pid#22496) during global destruction
!   <> DESTROY for DBI::dr=HASH(0x33b3308) ignored (inner handle gone)
!   >> DESTROY     DISPATCH (DBIx::ContextualFetch::db=HASH(0x33e60d8) rc1/1 @1 g2 ima10004 pid#22496) during global destruction
!   <> DESTROY for DBIx::ContextualFetch::db=HASH(0x33e60d8) ignored (inner handle gone)

trace for DBD::Oracle 1.76
....
!   >> DESTROY     DISPATCH (DBI::dr=HASH(0x556494047aa0) rc1/1 @1 g2 ima10004 pid#28793) during global destruction
    >> DESTROY DBI::dr=HASH(0x556494047aa0) clearing 1 CachedKids
!   -> DESTROY for DBD::Oracle::dr (DBI::dr=HASH(0x556494047aa0)~INNER) thr#5564920f3010
        OCIHandleFree(5564940d2480,OCI_HTYPE_ENV)=SUCCESS
!   <- DESTROY= ( undef ) [1 items] during global destruction
    DESTROY (dbih_clearcom) (drh 0x556494047a28, com 0x55649404b230, imp global destruction):
       FLAGS 0x102215: COMSET Active Warn PrintWarn ShowErrorStatement AutoCommit
       PARENT undef
       KIDS 1 (1 Active)
    dbih_clearcom 0x556494047a28 (com 0x55649404b230, type 1) done.
!   >> DESTROY     DISPATCH (DBIx::ContextualFetch::db=HASH(0x55649404e2c0) rc1/1 @1 g2 ima10004 pid#28793) during global destruction
!   -> DESTROY for DBD::Oracle::db (DBIx::ContextualFetch::db=HASH(0x55649404e2c0)~INNER) thr#5564920f3010
**Segmentation fault**

**Comment by djzort** [comment]
Its not a regression, thankfully

**Comment by djzort** [comment]
Is this related to https://github.com/perl5-dbi/DBD-Oracle/issues/35#issuecomment-453118036 ?

**Comment by djzort** [comment]
This is related https://github.com/perl5-dbi/DBD-Oracle/pull/79

**Comment by djzort** [comment]
My guess would be this commit, given that its dealing with disconnection https://github.com/perl5-dbi/DBD-Oracle/commit/591617a97ecf55d5b2323d49c366e8638b320d30

**Comment by CarstenGrohmann** [comment]
I'd like to confirm that this issue has been introduced with 591617a.

It looks like `XS_DBI_dispatch()` destroys the driver part of DBD::Oracle first and the database object later in a second step. This causes the segmenation violation because the environment handle has been already free'e before the database session has been closed (see @almirus in  https://github.com/perl5-dbi/DBD-Oracle/issues/65#issuecomment-453022681).

According to the Oracle documentation for "Terminating the Application" (https://docs.oracle.com/cd/B28359_01/appdev.111/b28395/oci02bas.htm#LNOCI87617) the connection shutdown has 4 steps:

1. Delete the user session by calling `OCISessionEnd()` for each session.
2. Delete access to the data source(s) by calling `OCIServerDetach()` for each source.
3. Explicitly deallocate all handles by calling `OCIHandleFree()` for each handle.
4. Delete the environment handle, which deallocates all other handles associated with it.

But in our case the environment handle is already free'd if `OCISessionEnd()` is called.

The issue will be probably done if the the dispatch ensures that `dbd_db_disconnect()` is executed first.

**Comment by djzort** [comment]
Perhaps here then? https://github.com/perl5-dbi/DBD-Oracle/commit/591617a97ecf55d5b2323d49c366e8638b320d30#diff-910bff34a0a9cc85c863b926e3fe02b9

**Comment by CarstenGrohmann** [comment]
> Perhaps here then? [591617a#diff-910bff34a0a9cc85c863b926e3fe02b9](https://github.com/perl5-dbi/DBD-Oracle/commit/591617a97ecf55d5b2323d49c366e8638b320d30#diff-910bff34a0a9cc85c863b926e3fe02b9)

Yes, this is it, probably. The code itself looks fine, but I think it's at the wrong place.

I'll me explain shortly why I think so.

Let's start with traces added by @almirus in https://github.com/perl5-dbi/DBD-Oracle/issues/65#issuecomment-453022681. Both traces shows the driver destroy function at line 3:

Trace output from DBD::Oracle 1.74:
```
!   -> DESTROY in DBD::_::common for DBD::Oracle::dr (DBI::dr=HASH(0x33b3380)~INNER) thr#1e57010
```
`dbd_dr_destroy()` does not exists, thereby the (empty?) default is used.


Trace output from DBD::Oracle 1.76:
```
!   -> DESTROY for DBD::Oracle::dr (DBI::dr=HASH(0x556494047aa0)~INNER) thr#5564920f3010
        OCIHandleFree(5564940d2480,OCI_HTYPE_ENV)=SUCCESS
```
Now `dbd_dr_destroy()` is implemented and calls `OCIHandleFree(OCI_HTYPE_ENV)`. This causes a segfault later in `dbd_db_disconnect()`.

After following some execution paths and reading sources, I think also (but I'm not quite sure) that DBI::dispatch (https://github.com/perl5-dbi/dbi/blob/0717caee91f6d44d14710676008811e93cc62d57/DBI.xs#L3497) executes `dbd_dr_destroy()` earlier than `ora_db_disconnect()`.

Based on both findings, I think the code itself is right, but placed wrong.

A possible solution is written down on DBI::DBD in paragraph "The disconnect_all() method":

> If you need to release any resources when the driver is unloaded, you can provide a disconnect_all method.

(https://metacpan.org/pod/DBI::DBD#The-disconnect_all()-method) 

I suggest to move the code from `dbd_dr_destroy()` to `dbd_discon_all()` (it's an alias for `disconnect_all()`).

What you do think about this?

**Comment by djzort** [comment]
@CarstenGrohmann give it a try? see if things crash still?

**Comment by CarstenGrohmann** [comment]
@djzort I did a quick hack only and moved 

```
if (imp_drh->envhp) {
	/* Free cached environment handle. */
	OCIHandleFree_log_stat(imp_drh, imp_drh->envhp, OCI_HTYPE_ENV, status);
}
```

from `dbd_dr_destroy()` to `dbd_discon_all()` (don't forget to add `return TRUE;`).

With this change I didn't see any crashes. 

I still need to investigate if the new place to free the handles is the best option especially in combination with 11cac2d.

What do you think about this change?

**Comment by djzort** [comment]
It's in the disconnect login, so can't break peoples toys too badly.

Can you do a PR so people can play with it?

**Comment by CarstenGrohmann** [comment]
I can do so, but it may take a while ...

**Comment by djzort** [comment]
Can you upload a diff/patch file?

**Comment by CarstenGrohmann** [comment]
I'm struggling with my fix currently.

Instead of providing my change, I'd like to discuss the shutdown sequence, first. Currently the drivers interface will be destroyed first and the database level interface in a second step.

This is visible in the DBI trace provided by almirus.

For Oracle we should do a shutdown in 3 steps:
 1. Shutdown active statements
 2. Shutdown the database interface
 3. Shutdown the driver interface

I assume, that the bug will be gone with this shutdown sequence. I'll ask on DBI developer/implementer mailing list during the next days.

**Comment by djzort** [comment]
Unfortunately, shifting this repo to perl5-dbi hasnt been as helpful as i was hoping. i might post a call for assistance on blogs.perl.org

**Comment by mjegh** [comment]
@djzort I have contributed quite a lot in the past but got frustrated with a number of issues with the maintenance of DBD::Oracle. Although my work is still dependent on DBD::Oracle I have far less time to help than I used to. Other fairly regular contributors have pretty much disappeared now as well. I still watch D::O and if I see anything I can help with I try to pitch in - this one didn't really attract my attention and I wasn't experiencing it but @CarstenGrohmann's suggestion to move the OCIHandleFree_log_stat doesn't sound too outrageous to me.

**Comment by djzort** [comment]
I wasnt meaning to be critical of anyone. I hope thats not what has been gleaned from my last comment. More than I was hoping someone would merge and close the PR's etc.

My involvement is for $client and I am vastly out of my depth messing around in XS. Ive just been lucky to beg a few XS pointers from tonyc via irc.

$client uses DBD::Oracle and although we have been asking to allocate some money to hire someone with XS and DBI skills, that hasnt happened yet. And since most of our software is mod_perl - crashing on exit isnt causing problems.

**Comment by mjegh** [comment]
@djzort I didn't take it as criticism. If there are PRs still to merge ping me and I'll do it.

**Comment by djzort** [comment]
@mjegh I have pinged you on a couple to close and one to merge

**Comment by mjegh** [comment]
@djzort I think I've done them all - let me know if not.

**Comment by djzort** [comment]
@mjegh looks good, thanks muchly. This https://github.com/perl5-dbi/DBD-Oracle/issues/35#event-2229153989 probably is worth a release to the cpan

**Comment by mjegh** [comment]
@djzort I agree. I have been unable to build a D::O distribution for upload to CPAN for ages now but I'll help in any way I can.

**Comment by djzort** [comment]
@mjegh its all via Dist::Zilla now - I cleaned that all up in 1.75

**Comment by CarstenGrohmann** [comment]
It looks like the environment handle is stored at `imp_drh` to use one environment over all connections.  But as discussed earlier freeing is failing. 

A workaround is to don't store the environment handle at `imp_drh`:
```
--- a/dbdimp.c
+++ b/dbdimp.c
@@ -769,8 +769,8 @@ dbd_db_login6(SV *dbh, imp_dbh_t *imp_dbh, char *dbname, char *uid, char *pwd, S
 #ifdef ORA_OCI_112
                        if (!imp_dbh->using_drcp)
 #endif
-                               if (!imp_drh->envhp)    /* cache first envhp info drh as future default */
-                                       imp_drh->envhp = imp_dbh->envhp;
+//                             if (!imp_drh->envhp)    /* cache first envhp info drh as future default */
+//                                     imp_drh->envhp = imp_dbh->envhp;
 
                        /* update the hard-coded csid constants for unicode charsets */
                        utf8_csid          = OCINlsCharSetNameToId(imp_dbh->envhp, (void*)"UTF8");
```

**Comment by djzort** [comment]
That seems like an optimization only?

**Comment by CarstenGrohmann** [comment]
No, it's a feature to use the same OCI environment for all connections. The section "ora_envhp" in 
[Oracle.pm](https://github.com/perl5-dbi/DBD-Oracle/blob/8323b283147f93af11d7aa01cbeb3a3dc2f094b9/lib/DBD/Oracle.pm#L1802) describes the behaviour.

**Comment by djzort** [comment]
If i build perl without threads, i dont see any crashes. For whatever thats worth

**Comment by djzort** [comment]
Related https://rt.cpan.org/Ticket/Display.html?id=72577&results=b68bd41784fffaa2769c7583a0792838

**Comment by CarstenGrohmann** [comment]
Please test and comment #89. 

A better and more safe solution would be reference counting to drh->envhp.

**Comment by CarstenGrohmann** [comment]
> Related https://rt.cpan.org/Ticket/Display.html?id=72577&results=b68bd41784fffaa2769c7583a0792838

@djzort: Isn't this more related to wrong type in `enable_taf()` as discussed in #35 and thereby already fixed in the master branch?
