### ISSUE TITLE
t/25plsql.t: "test bind_param_inout for non assigned" fails for Instant Client 18.3

### ISSUE THREAD

**Issue by whindsx** [perl5-dbi/DBD-Oracle#70]
It appears the problem (http://www.mail-archive.com/dbi-users@perl.org/msg18835.html) that this originally tested for has appeared again:

- Perl 5.26.2
- DBI 1.641
- Oracle Instant Client 18.3.0.0
- Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
- Oracle Linux 4.1.12-124.19.1.el6uek.x86_64

```
my $sth = $dbh->prepare (q(
    BEGIN
 --     :p1 := :p1 ;
 --     :p2 := :p2 ;
        IF  :p2 != :p3 THEN
            :p1 := 'AAA' ;
            :p2 := 'Z' ;
        END IF ;
END ;));

{
    my ($p1, $p2, $p3) = ('Hello', 'Y', 'Y') ;
    $sth->bind_param_inout(':p1', \$p1, 30) ;
    $sth->bind_param_inout(':p2', \$p2, 1) ;
    $sth->bind_param_inout(':p3', \$p3, 1) ;
    note("Before p1=[$p1] p2=[$p2] p3=[$p3]\n");
    ok($sth->execute, 'test bind_param_inout for non assigned');
    is($p1, 'Hello', 'p1 ok');
    is($p2, 'Y', 'p2 ok');
    is($p3, 'Y', 'p3 ok');
    note("After p1=[$p1] p2=[$p2] p3=[$p3]\n");
}

```

```
t/25plsql.t ............... 63/82 
#   Failed test 'p1 ok'
#   at t/25plsql.t line 283.
#          got: ''
#     expected: 'Hello'

#   Failed test 'p2 ok'
#   at t/25plsql.t line 284.
#          got: ''
#     expected: 'Y'
# Looks like you failed 2 tests of 82.
```

Un-commenting the assignments does fix the issue as described in the original email. I also verified that this test passed against older client versions of 11.2 and 12.2.

**Comment by cjbj** [comment]
I haven't seen issues with character OUT binds, but there are lower issues in the Oracle stack for some descriptor types that are pending fixes from Oracle. The takeaway is that applications must initialize all PL/SQL OUT binds in the PL/SQL block, otherwise behavior is unpredictable i.e will fail in some cases. Some related discussion is in https://github.com/oracle/node-oracledb/issues/886 This is tracked in Oracle bug 22813401.

I'll be interested to see whether this DBD::Oracle issue is related.

**Comment by kjetillll** [comment]
Maybe `:p1 := :p1;` and `:p2 := :p2;` should be uncommented in 25plsql.t and a `warn` in `sub bind_param_inout` for anon pl/sql without `:pX:=:pX` for each bind var after `BEGIN` for certain versions of Oracle?

**Comment by whindsx** [comment]
This is still happening in Oracle Instant Client 18.5.0.0.0.

@cjbj I can't find the Oracle bug you mentioned. Can you give us an update on that and if it's related?

The @kjetillll solution sounds reasonable.

**Comment by djzort** [comment]
Would someone like to build a patch for this?

It would also be good to get instant client 18.5 in to travis

**Comment by djzort** [comment]
I dont understand the issue well enough to comment on the pr. Can someone explain it to me like im 5?

**Comment by whindsx** [comment]
> 
> 
> I dont understand the issue well enough to comment on the pr. Can someone explain it to me like im 5?

- For a long time OCI plays nice
- Suddenly OCI plays mean
- Perl devs create **The Test** to detect OCI versions that don't play nice
- OCI plays nice again for a long time
- OCI decides to start playing mean again
- **The Test** begins to detect mean OCI
-  New OCI versions do not play nice anymore and always fail **The Test**

So the **The Test** should now just inform devs of how OCI doesn't play like it used to (rather than fail if it's a mean version). Maybe someday OCI plays like it used to again.

Note: @kjetillll also suggested that we modify `sub bind_param_inout` to actually do the warning but I personally am not prepared to spend that much time on this.

**Comment by djzort** [comment]
FYI i have added 18.3 and 18.5 to travis

**Comment by djzort** [comment]
> Maybe `:p1 := :p1;` and `:p2 := :p2;` should be uncommented in 25plsql.t and a `warn` in `sub bind_param_inout` for anon pl/sql without `:pX:=:pX` for each bind var after `BEGIN` for certain versions of Oracle? Otherwise some might not upgrade Oracle just because of this.

My understanding now is that this is a regression in instantclient and based on the comments from the node bug https://github.com/oracle/node-oracledb/issues/886 there isnt much we can do about it.

I dont like warnings as they are ignored. Folks will just run cpanm and never even see them, but bombing out entirely isn't helpful either.

So my suggestion is to make the test more nuanced. 

- Test using both the commented and the uncommented sql, as the variables are supposed to be initialized
- Create a known list of known bad instantclients for this issue (just in the .t file)
- Add an environment variable that allows the issue to be ack'd and the test to pass if the client is known bad
- Continue to catch this issue for new instantclients

**Comment by cjbj** [comment]
Technically it's not a regression; it's always been undefined behavior. The question is how to get it stable - I'll prod the code owner again, but it's a protocol change so is not trivial.

**Comment by djzort** [comment]
Revised solution:

- Test using both the commented and the uncommented sql, as the variables are supposed to be initialized
- Create a known list of known bad instantclients for this issue (just in the .t file)
- Skip the test for known bad
- Continue to catch this issue/nonfeature/behaviour for new instantclients

**Comment by djzort** [comment]
FYI instantclient 19.6 has been added to Travis

**Comment by whindsx** [comment]
> 
> 
> Revised solution:
> 
>     * Test using both the commented and the uncommented sql, as the variables are supposed to be initialized
> 
>     * Create a known list of known bad instantclients for this issue (just in the .t file)
> 
>     * Skip the test for known bad
> 
>     * Continue to catch this issue/nonfeature/behaviour for new instantclients

I've got a PR together for this as described. I have the following list of known "bad" clients (9.2, 18.3, 18.5, 19.6, 19.8). I'm wondering if I should not include 19.8 since we are not testing against it in Travis yet?

**Comment by djzort** [comment]
Changes to test merged
