### ISSUE TITLE
Build DBD::Oracle on Debian systems without LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by eserte** [perl5-dbi/DBD-Oracle#72]
On Debian systems with Oracle instantclient (e.g. version 12.1) it was always possible (at least with Debian/wheezy and Debian/jessie) to build a DBD::Oracle which was able to work *without* setting LD_LIBRARY_PATH.
Unfortunately, this does not seem to be possible with Debian/stretch (the current stable). When building DBD::Oracle as usual, then all tests fail with:
```
#          got: 'install_driver(Oracle) failed: Can't load '/home/somebody/.cpan/build/DBD-Oracle-1.74-0/blib/arch/auto/DBD/Oracle/Oracle.so' for module DBD::Oracle: libnnz12.so: cannot open shared object file: No such file or directory at /opt/perl-5.12.3/lib/5.12.3/x86_64-linux/DynaLoader.pm line 200.
```
The following change can be used on these systems as a workaround:
```
diff --git a/Makefile.PL b/Makefile.PL
index d4eb5ae..7200358 100755
--- a/Makefile.PL
+++ b/Makefile.PL
@@ -1109,6 +1109,7 @@ sub read_sysliblist {
        $linkwith =~ m/-lcl\b/ or
            $syslibs =~ s/\s*-lcl\b//g;
     }
+    $syslibs .= " -lnnz12 -lons -lclntshcore";
     return $syslibs;
 }
 
```
Of course, this has to be done in a better way (conditionally? maybe when a specific instantclient version is detected?).

**Comment by whindsx** [comment]
How/where did you go about installing your Oracle Instant Client? My pull request #71 might cover this.

**Comment by alexm** [comment]
> Unfortunately, this does not seem to be possible with Debian/stretch (the current stable). When building DBD::Oracle as usual, then all tests fail with:
> 
> ```
> #          got: 'install_driver(Oracle) failed: Can't load '/home/somebody/.cpan/build/DBD-Oracle-1.74-0/blib/arch/auto/DBD/Oracle/Oracle.so' for module DBD::Oracle: libnnz12.so: cannot open shared object file: No such file or directory at /opt/perl-5.12.3/lib/5.12.3/x86_64-linux/DynaLoader.pm line 200.
> ```

You're right, I just found out a few days after uploading 1.74-5 to Debian unstable while trying to test the package outside the Oracle box where I usually build and test it.

> ```
> +    $syslibs .= " -lnnz12 -lons -lclntshcore";
> ```

I will try this and upload a new release into unstable.

> Of course, this has to be done in a better way (conditionally? maybe when a specific instantclient version is detected?).

Right now, the Debian package dependencies state OCI 12.1 only. I was planning to test the 18.x release but the perl5.28 transition required a prompt rebuild.

Debian 10 (Buster) full freeze is due by mid March, so there's still time to add improvements to DBD::Oracle in Debian before that. Just let me know how can I help.

**Comment by eserte** [comment]
@whindsx: the instantclient rpm provided by Oracle is turned into a .deb using `alien` and installed with `apt`. `perl Makefile.PL` is called with the options `-h` and `-V`, as auto-detection does not work. It seems that #71 could solve the auto-detection problem.

**Comment by whindsx** [comment]
@eserte I tested on Debian (9.6) as described and #71 does not fix the issue. :(

**Comment by alexm** [comment]
@eserte, I added `-lipc1 -lmql1` that were also missing in Oracle.so and now ldd reports all libs found without defining `LD_LIBRARY_PATH`. Kudos for the patch!

I'm going to release a new Debian version with this patch. Thanks a lot.

**Comment by djzort** [comment]
Can we curate this in to a patch for inclusion?

**Comment by djzort** [comment]
@eserte can you make this a PR please?

**Comment by eserte** [comment]
@djzort: The diff is good enough as a workaround for debian/stretch, but not good enough as a general solution. So no PR with this diff from me.
