### ISSUE TITLE
Review rt.cpan.org issues

### ISSUE THREAD

**Issue by djzort** [perl5-dbi/DBD-Oracle#75]
Theres lots of bugs here, some might be solved: https://rt.cpan.org/Dist/Display.html?Queue=DBD-Oracle

**Comment by djzort** [comment]
@mjegh i believe you opened all these. Perhaps they can be copied her in to GH and closed on RT?

- https://rt.cpan.org/Ticket/Display.html?id=90068
- https://rt.cpan.org/Ticket/Display.html?id=85886
- https://rt.cpan.org/Ticket/Display.html?id=83766
- https://rt.cpan.org/Ticket/Display.html?id=72898
- https://rt.cpan.org/Ticket/Display.html?id=64752

I believe these two are fixed?

- https://rt.cpan.org/Ticket/Display.html?id=78977
- https://rt.cpan.org/Ticket/Display.html?id=69305

**Comment by abraxxa** [comment]
And please update the meta info for the bugtracker to point here, I always land on RT and open the bug reports there.

**Comment by mjegh** [comment]
Updated bugtracker to github and home page to metacpan in cfc917669469cb841e3c953e7ea544aa3a3ba71e

**Comment by mjegh** [comment]
Not sure what to do with RT83766 and RT72898 but I've had a bit of a clear out.

**Comment by mjegh** [comment]
All done.
