### ISSUE TITLE
Enable travis

### ISSUE THREAD

**Issue by djzort** [perl5-dbi/DBD-Oracle#87]
Would someone be so kind as to enable travis for this repo? thanks

**Comment by mjegh** [comment]
If you remind me how, I will.

**Comment by djzort** [comment]
Looks like it just needs a nudge at https://travis-ci.org/perl5-dbi/DBD-Oracle

**Comment by mjegh** [comment]
@dzort I may have done as you asked.

**Comment by djzort** [comment]
Would you be so kind as to manually trigger a build on master?

**Comment by mjegh** [comment]
Done

**Comment by djzort** [comment]
terrific, thanks @mjegh
