### ISSUE TITLE
Travis is failing with `fatal: Not a valid object name undefined`

### ISSUE THREAD

**Issue by CarstenGrohmann** [perl5-dbi/DBD-Oracle#94]
I summary the current failing of Travis CI here, because it looks like more an `dzil build` / git issue.

Currently Travis is failing with `fatal: Not a valid object name undefined` during setup the test environment. 

One difference I found is the git branch used by the two Travis runs:

- failing using master branch: [perl5-dbi/DBD-Oracle#93](https://travis-ci.org/perl5-dbi/DBD-Oracle/jobs/549089108)
- successfull using branch [destroy_envhp_with_last_dbh](https://travis-ci.org/ByteFoundryAU/DBD-Oracle/jobs/549085384)
 
This is the error message with a little bit more content:
```
[CopyrightYearFromGit] Setting copyright_year to 2019
[DZ] beginning to build DBD-Oracle
[ReadmeMarkdownFromPod] someone tried to munge lib/DBD/Oracle.pm after we read from it. Making modifications again...
[DZ] writing DBD-Oracle in /home/travis/build/perl5-dbi/DBD-Oracle/build_dir
[CopyFilesFromBuild] Copied /home/travis/build/perl5-dbi/DBD-Oracle/build_dir/cpanfile to cpanfile
fatal: Not a valid object name undefined
The command "build-dist" failed and exited with 128 during .
```

From the Travis log I reconnstructed the execution stack:
1. few unknown steps
2. `before_install`
3. `build-dist` (from Travis build helpers for Perl)
4. `dzil build` build the tree based on `dist.ini`
5. `CopyFilesFromBuild` has been finished successfully
6. Unkown command `dzil build` is failing with `fatal: Not a valid object name undefined`

See also: travis-perl/helpers/issues/74

@djzort: Do you have any idea which part of `dzil build` is failing. Could it be a git command?

**Comment by djzort** [comment]
Thanks for making a new GH issue.

A quick google, indicates that the text "fatal: Not a valid object name XXXXX" seems to come from git software itself. I can't replicate it, though this could be because of differing git versions (guess)

**Comment by djzort** [comment]
The .travis.yml file is identical to Moo: https://github.com/moose/Moo/blob/master/.travis.yml

**Comment by djzort** [comment]
I dont think this is build-dist, but something in dist::zilla. I tried turning off some of the Git:: plugins to Dzil, but that didnt help.

**Comment by mjegh** [comment]
This is fixed.
